let promise = new Promise((resolve, reject) => {
  setTimeout(() => {
     //resolve(console.log ("resolved successfully"))   
     reject("OOps!!!")

  },2000);
})

promise.then((response) => {
  console.log("Here is the resolved response");
  console.log(response)
}).catch( err => {
  console.log(err)
})


console.log("First PArt");